/**
 * Locale content access.
 *
 * The four JSON files are generated by `npm run content:extract` and verified
 * key-for-key by `npm run content:check`, so a lookup that succeeds in one
 * locale is guaranteed to succeed in the others. Everything is imported
 * statically - this is a static build with no runtime content fetching.
 */
import { LOCALES, DEFAULT_LOCALE, LEGAL_PAGES, type LegalPageId, type Locale } from '@/config/site';
import fr from '@/content/i18n/fr.json';
import en from '@/content/i18n/en.json';
import de from '@/content/i18n/de.json';
import it from '@/content/i18n/it.json';

/** Shape is defined by the FR file, which the parity check treats as the reference. */
export type Content = typeof fr;

const CONTENT: Record<Locale, Content> = {
  fr,
  en: en as unknown as Content,
  de: de as unknown as Content,
  it: it as unknown as Content,
};

export const getContent = (locale: Locale): Content => CONTENT[locale];

/** Prefix a root-relative path with the locale: ("/privacy/", "de") -> "/de/privacy/" */
export function localePath(path: string, locale: Locale): string {
  const clean = path.replace(/^\/+/, '');
  return `/${locale}/${clean}`;
}

/** The URL of a legal page in one language: ("cookies", "fr") -> "/fr/cookies/" */
export function legalPath(page: LegalPageId, locale: Locale): string {
  return `/${locale}/${LEGAL_PAGES[page][locale]}`;
}

/**
 * Any locale's slug back to the page it belongs to.
 *
 * The legal and photo-credits pages have a DIFFERENT slug per language -
 * /fr/mentions-legales/ and /en/legal-notice/ are one page. Without this the
 * language switcher only swapped the prefix and left the slug alone, so
 * switching to German from the Italian credits page asked for
 * /de/crediti-foto/, which does not exist. Every one of those pages 404'd in
 * three languages out of four.
 */
const SLUG_TO_PAGE = new Map<string, LegalPageId>(
  Object.entries(LEGAL_PAGES).flatMap(([page, slugs]) =>
    Object.values(slugs).map((slug) => [slug, page as LegalPageId] as const),
  ),
);

/** The equivalent of a path in another language, slug included. */
export function pathForLocale(currentPath: string, locale: Locale): string {
  const page = SLUG_TO_PAGE.get(currentPath.replace(/^\/+/, ''));
  return page ? legalPath(page, locale) : localePath(currentPath, locale);
}

/** All locales with their metadata, for the language switcher and hreflang tags. */
export function localeAlternates(currentPath: string) {
  // currentPath is the path *within* a locale, e.g. "" or "privacy/".
  return LOCALES.map((locale) => ({
    locale,
    ...CONTENT[locale].meta,
    path: pathForLocale(currentPath, locale),
  }));
}

export { LOCALES, DEFAULT_LOCALE, type Locale };
