import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import QRCode from 'qrcode';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = resolve(ROOT, 'qr');

const BOOK_PAGE_PATH = '/livre';
const TARGET = `https://www.mhsv.ch${BOOK_PAGE_PATH}`;

if (!/^https:\/\/www\.mhsv\.ch\/livre$/.test(TARGET)) {
  throw new Error(`Refusing to encode "${TARGET}" - not the approved permanent URL`);
}
if (/\.pdf|drive\.|dropbox|s3\.|bit\.ly/i.test(TARGET)) {
  throw new Error('Refusing to encode a file, storage or shortener URL');
}

const DARK = '#0C1D3A'; // brand navy - high contrast on white
const LIGHT = '#FFFFFF';
const QUIET_ZONE_MODULES = 4;
const DPI = 300;
const mmToPx = (mm) => Math.round((mm / 25.4) * DPI);

if (process.env.MHSV_QR_APPROVED !== 'yes') {
  console.error('');
  console.error('  QR generation is gated.');
  console.error('');
  console.error('  Before generating the file that goes to print:');
  console.error(`    1. ${TARGET} must be live over HTTPS on the real domain`);
  console.error('       (verify with: AUDIT_BASE_URL=https://www.mhsv.ch npm run check:qr)');
  console.error('    2. MHSV® must have approved the destination page in writing');
  console.error('');
  console.error('  Then run:  MHSV_QR_APPROVED=yes npm run qr');
  console.error('');
  process.exit(1);
}

mkdirSync(OUT, { recursive: true });

const options = {
  errorCorrectionLevel: 'M',
  margin: QUIET_ZONE_MODULES,
  color: { dark: DARK, light: LIGHT },
};

const decodeSegment = (data) =>
  typeof data === 'string' ? data : new TextDecoder().decode(Uint8Array.from(data));

const encoded = QRCode.create(TARGET, options).segments.map((s) => decodeSegment(s.data)).join('');
if (encoded !== TARGET) {
  throw new Error(`QR payload mismatch: encoded "${encoded}", expected "${TARGET}"`);
}

const svg = await QRCode.toString(TARGET, { ...options, type: 'svg' });
writeFileSync(resolve(OUT, 'mhsv-livre-qr.svg'), svg);

const sizes = [30, 25];
for (const mm of sizes) {
  const px = mmToPx(mm);
  const buffer = await QRCode.toBuffer(TARGET, { ...options, type: 'png', width: px });
  writeFileSync(resolve(OUT, `mhsv-livre-qr-${mm}mm.png`), buffer);
}

const modules = QRCode.create(TARGET, options).modules.size;

writeFileSync(
  resolve(OUT, 'README.md'),
  [
    '# Founding Book QR code - print assets',
    '',
    'Generated by `npm run qr`. **Do not edit these files by hand.**',
    '',
    `- Encoded URL: \`${TARGET}\` (verified by round-trip on generation)`,
    `- Symbol: ${modules}×${modules} modules, error correction M`,
    `- Quiet zone: ${QUIET_ZONE_MODULES} modules on every side (already included in the files)`,
    `- Colour: ${DARK} on ${LIGHT}`,
    '',
    '| File | Use |',
    '| --- | --- |',
    '| `mhsv-livre-qr.svg` | Vector - supply this to the layout specialist |',
    `| \`mhsv-livre-qr-30mm.png\` | 300 dpi raster, ${mmToPx(30)}px = 30 mm |`,
    `| \`mhsv-livre-qr-25mm.png\` | 300 dpi raster, ${mmToPx(25)}px = 25 mm |`,
    '',
    '## Placement (from the client brief)',
    '',
    '- Back cover, lower-right or lower-centre. Never the front cover.',
    '- 25–30 mm square. Do not scale beyond that range.',
    '- Do not distort, rotate, add a shadow, or place any graphic over it.',
    '- Keep the quiet zone clear - do not crop the white margin out of the file.',
    '- Print the URL in text beneath the code, with the bilingual caption.',
    '- The same file serves the FR and EN editions: the destination is bilingual.',
    '',
    '## Before print',
    '',
    '1. The destination page must be live over HTTPS and approved by MHSV®.',
    '2. Test on a printed proof with several phones, operating systems and',
    '   scanner apps - not only on screen.',
    '3. Verify the printed URL below the code matches the encoded one.',
    '4. Obtain written approval of the proof before either edition is printed.',
    '',
    '## Not published on the web',
    '',
    'These are print assets and are intentionally outside `public/`, so they are',
    'never served. The website shows the order button as the primary action; the',
    'QR is optional there.',
    '',
  ].join('\n'),
);

console.log(`  ✓ qr/mhsv-livre-qr.svg          vector`);
for (const mm of sizes) {
  console.log(`  ✓ qr/mhsv-livre-qr-${mm}mm.png     ${mmToPx(mm)}px @ 300dpi = ${mm}mm`);
}
console.log(`  ✓ qr/README.md`);
console.log(`\n  Encoded and verified: ${TARGET}`);
console.log(`  Symbol ${modules}×${modules} modules, quiet zone ${QUIET_ZONE_MODULES} modules.`);
